######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2021, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/home/vlb19/Documents/Coding/My_work/PhD-code/Results/busco_results/ResultsSummary/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Ordospora colligata OC4', 'Ordospora colligata OC4', 'Ordospora colligata OC4', 'Ordospora colligata OC4', 'Edhazardia aedis USNM 41457', 'Edhazardia aedis USNM 41457', 'Edhazardia aedis USNM 41457', 'Edhazardia aedis USNM 41457', 'Hamiltosporidium tvaerminnensis', 'Hamiltosporidium tvaerminnensis', 'Hamiltosporidium tvaerminnensis', 'Hamiltosporidium tvaerminnensis', 'Hepatospora eriocheir', 'Hepatospora eriocheir', 'Hepatospora eriocheir', 'Hepatospora eriocheir', 'Vittaforma corneae ATCC 50505', 'Vittaforma corneae ATCC 50505', 'Vittaforma corneae ATCC 50505', 'Vittaforma corneae ATCC 50505', 'Enterocytozoon bieneusi', 'Enterocytozoon bieneusi', 'Enterocytozoon bieneusi', 'Enterocytozoon bieneusi', 'Pseudoloma neurophilia ASM143216v1', 'Pseudoloma neurophilia ASM143216v1', 'Pseudoloma neurophilia ASM143216v1', 'Pseudoloma neurophilia ASM143216v1', 'Trachipleistophora hominis', 'Trachipleistophora hominis', 'Trachipleistophora hominis', 'Trachipleistophora hominis', 'Vairimorpha ceranae GCF 000988165', 'Vairimorpha ceranae GCF 000988165', 'Vairimorpha ceranae GCF 000988165', 'Vairimorpha ceranae GCF 000988165', 'Enterocytozoon hepatopenaei', 'Enterocytozoon hepatopenaei', 'Enterocytozoon hepatopenaei', 'Enterocytozoon hepatopenaei', 'Anncaliia algerae PRA339', 'Anncaliia algerae PRA339', 'Anncaliia algerae PRA339', 'Anncaliia algerae PRA339', 'Spraguea lophii 42 110', 'Spraguea lophii 42 110', 'Spraguea lophii 42 110', 'Spraguea lophii 42 110', 'Mitosporidium daphniae', 'Mitosporidium daphniae', 'Mitosporidium daphniae', 'Mitosporidium daphniae', 'Encephalitozoon cuniculi', 'Encephalitozoon cuniculi', 'Encephalitozoon cuniculi', 'Encephalitozoon cuniculi', 'Nematocida parisii ERTm1', 'Nematocida parisii ERTm1', 'Nematocida parisii ERTm1', 'Nematocida parisii ERTm1', 'Enterospora canceri', 'Enterospora canceri', 'Enterospora canceri', 'Enterospora canceri', 'Vavraia culicis floridensis', 'Vavraia culicis floridensis', 'Vavraia culicis floridensis', 'Vavraia culicis floridensis', 'Vairimorpha apis BRL01', 'Vairimorpha apis BRL01', 'Vairimorpha apis BRL01', 'Vairimorpha apis BRL01', 'Encephalitozoon romalae SJ-2008', 'Encephalitozoon romalae SJ-2008', 'Encephalitozoon romalae SJ-2008', 'Encephalitozoon romalae SJ-2008', 'Vairimorpha bombycis CQ1', 'Vairimorpha bombycis CQ1', 'Vairimorpha bombycis CQ1', 'Vairimorpha bombycis CQ1', 'Nematocida sp', 'Nematocida sp', 'Nematocida sp', 'Nematocida sp', 'Encephalitozoon hellem ATCC 50504', 'Encephalitozoon hellem ATCC 50504', 'Encephalitozoon hellem ATCC 50504', 'Encephalitozoon hellem ATCC 50504', 'Encephalitozoon intestinalis ATCC 50506', 'Encephalitozoon intestinalis ATCC 50506', 'Encephalitozoon intestinalis ATCC 50506', 'Encephalitozoon intestinalis ATCC 50506')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(98.3, 0.7, 0.0, 1.0, 90.0, 0.7, 4.8, 4.5, 62.5, 26.3, 3.3, 7.9, 43.8, 0.2, 2.7, 53.3, 73.8, 1.2, 3.7, 21.3, 50.2, 4.3, 1.5, 44.0, 64.8, 0.2, 2.7, 32.3, 83.2, 0.0, 5.0, 11.8, 97.0, 0.2, 1.0, 1.8, 52.2, 4.5, 1.5, 41.8, 74.5, 1.8, 2.2, 21.5, 90.8, 0.3, 4.0, 4.9, 32.3, 1.7, 3.0, 63.0, 99.2, 0.2, 0.2, 0.4, 96.3, 0.2, 1.5, 2.0, 52.3, 1.2, 1.5, 45.0, 95.3, 0.7, 1.8, 2.2, 54.8, 2.5, 8.8, 33.9, 98.3, 0.0, 1.2, 0.5, 46.3, 27.7, 6.5, 19.5, 99.5, 0.2, 0.0, 0.3, 99.2, 0.2, 0.5, 0.1, 99.2, 0.2, 0.2, 0.4)
my_values <- c(590, 4, 0, 6, 540, 4, 29, 27, 375, 158, 20, 47, 263, 1, 16, 320, 443, 7, 22, 128, 301, 26, 9, 264, 389, 1, 16, 194, 499, 0, 30, 71, 582, 1, 6, 11, 313, 27, 9, 251, 447, 11, 13, 129, 545, 2, 24, 29, 194, 10, 18, 378, 595, 1, 1, 3, 578, 1, 9, 12, 314, 7, 9, 270, 572, 4, 11, 13, 329, 15, 53, 203, 590, 0, 7, 3, 278, 166, 39, 117, 597, 1, 0, 2, 595, 1, 3, 1, 595, 1, 1, 3)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
